routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for administrators. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', [HomeController::class, 'index']);
Route::get('/users', [HomeController::class, 'users']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/home', function () {
    foreach (auth()->user()->roles as $role) {
        $url = strtolower($role->title);
    }
    return redirect('/' . $url);
})->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', \App\Http\Controllers\TasksController::class);

    Route::resource('users', \App\Http\Controllers\UsersController::class);
});

app/Http/Controllers/Agent/HomeController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Policy;

class HomeController extends Controller
{
    public function index()
    {
        return view('agent.index');
    }

    public function partners()
    {
        //abort_if(Gate::denies('user_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::with('roles')->get();

        return view('agent.partners', compact('users'));
    }

    public function policyIndex()
    {
        foreach(auth()->user()->roles as $role){
            $user_role = $role;
        }

        switch ($user_role) {
            case 'Admin':
                $policies = Policy::get();
                break;
            case 'Agent':
                $policies = Policy::whereAgent_id(auth()->user()->id)->get();
                break;
            case 'Partner':
                $policies = Policy::wherePartner_id(auth()->user()->id)->get();
                break;
            case 'Promoter':
                $policies = Policy::wherePromoter_id(auth()->user()->id)->get();
                break;
            case 'Client':
                $policies = Policy::whereUser_id(auth()->user()->id)->get();
                break;

            default:
                $policies = Policy::get();
                break;
        }

        return view('client.policies.index', compact('policies'));
    }

    public function policyRequest()
    {
        return view('client.policies.request');
    }

    public function policyRegister(Request $request)
    {
        $promoter_id = NULL;
        $partner_id = NULL;
        $agent_id = NULL;

        if (auth()->user()->parent_id != NULL) {
            $promoter = User::find(auth()->user()->parent_id);
            foreach ($promoter->roles as $role){
                $user_role = $role->title;
            }
        }
        if ($promoter && $user_role == 'Promoter') {
            $promoter_id = $promoter->id;
            $partner = User::find($promoter->parent_id);
            foreach ($partner->roles as $role){
                $user_role = $role->title;
            }
        }
        if (!$partner && auth()->user()->parent_id != NULL) {
            $partner = User::find(auth()->user()->parent_id);
            foreach ($promoter->roles as $role){
                $user_role = $role->title;
            }
        }
        if ($partner && $user_role == 'Partner') {
            $partner_id = $partner->id;
            $agent = User::find($partner->id);
            foreach ($agent->roles as $role){
                $user_role = $role->title;
            }
        }
        if (!$agent && auth()->user()->parent_id != NULL) {
            $agent = User::find(auth()->user()->parent_id);
            foreach ($agent->roles as $role){
                $user_role = $role->title;
            }
        }
        if ($agent && $user_role == 'Agent') {
            $agent_id = $agent->id;
        }

        $user = Policy::create([
            'phone' => $request['phone'],
            'type' => $request['type'],
            'user_id' => auth()->user()->id,
            'promoter_id' => $promoter_id,
            'partner_id' => $partner_id,
            'agent_id' => $agent_id,
        ]);

        return redirect()->route('policies.index');
    }

    public function whatsapp($id){
        $policy = Policy::find($id);
        $url = "https://api.whatsapp.com/send?phone=" . $policy->phone . "&text=Hola, Soy " . auth()->user()->name . " de DataSeguros. Te contacto por tu solicitud de una póliza " . $policy->type . " con nosotros. ¿Cómo puedo ayudarte?";
        $policy->status = "Atendida";
        $policy->save();
        return redirect($url);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/agent/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/agent/partners.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content')
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Show User
        </h2>
    </x-slot>
    <div>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            {{--<div class="block mb-8">
                <a href="{{ route('users.create') }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add User</a>
            </div>--}}
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                <tr>
                                    <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ID
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Birthday
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Marital Status
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Roles
                                    </th>
                                    <th scope="col" width="200" class="px-6 py-3 bg-gray-50">

                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @php
                                        foreach (auth()->user()->roles as $role){
                                            $user_role_id = $role->id;
                                        }
                                    @endphp
                                @foreach ($users as $user)
                                    @foreach ($user->roles as $role)
                                        @if ($role->id > $user_role_id && ($user->parent_id == auth()->user()->id || $user->parent_id == NULL))
                                            <tr>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->id_type . $user->id_doc }}
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->name }}
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->email }}
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->birthday }}
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->marital_status }}
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                        {{ $role->title }}
                                                    </span>
                                                </td>

                                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                                    <a href="{{ route('users.show', $user->id) }}" class="text-blue-600 hover:text-blue-900 mb-2 mr-2">View</a>
                                                    <a href="{{ route('users.edit', $user->id) }}" class="text-indigo-600 hover:text-indigo-900 mb-2 mr-2">Edit</a>
                                                    <form class="inline-block" action="{{ route('users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('Are you sure?');">
                                                        <input type="hidden" name="_method" value="DELETE">
                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                        <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Delete">
                                                    </form>
                                                </td>
                                            </tr>
                                        @endif
                                    @endforeach
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop